name: mich
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - click=8.0.4
  - flask=2.2.2
  - intel-openmp=2023.1.0
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - pandas=1.5.3
  - pip=23.0.1
  - plotly=5.9.0
  - python=3.11.3
  - python-dateutil=2.8.2
  - pytz=2022.7
  - readline=8.2
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tk=8.6.12
  - tzdata=2023c
  - werkzeug=2.2.3
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
